// src/pages/fursona.vue
<template>
  <div>
    <BaseHead title="Fursona" description="About my fursona lol" />
    <TBA />
    <article
      class="max-w-screen-lg my-0 mx-auto px-7 leading-7 flex flex-col gap-y-3"
    >
      <div id="figure-container">
        <figure>
          <img src="/assets/static/08.png" />
          <figcaption>
            A blooshy boi
          </figcaption>
        </figure>
        <figure>
          <img src="/assets/static/sketch_jan2020_result.png" style="width: 26.8rem"/>
          <figcaption>
            A sketch from January 2022
          </figcaption>
        </figure>
        
      </div>
      <h2>Brief Description</h2>
      <p>
        <strong>Skep</strong> is a blue and yellow fox-husky hybrid or fusky;
        and was originally a husky. Propped with thick black glasses and wearing
        a purple t-shirt with white outlines, and completely pantless lmao
      </p>
      <p>
        Mixing with a typical traits both of a fox and a husky, he's a
        wholesome, outgoing, yet weird personality and he easily gets soft when
        he's immediately flattered and starts blushing intensely lol
      </p>
      <h2>History and background</h2>
      <p>
        My first attempt at making a fursona was around mid-2019 when I was
        listening to BLACKPINK almost every single day. Because of this - I
        tried making a fursona based on BLACKPINK's color palette on their EP
        <em>Kill This Love</em>.
      </p>

      <div id="figure-container">
        <figure>
          <img src="/assets/static/skep-early-2019.png" />
          <figcaption>
            A very and awful early head <br />design drawn from Photoshop in
            2019.
          </figcaption>
        </figure>
      </div>

      <p>
        But this was immediately scrapped because it turned out horrible due to
        a lack of drawing skills. Yes, I've known about bases that I could color
        from, but I'm still indecisive about how the design will turn out to be
        at the time.
      </p>

      <p>
        During lockdown time, when BTS released their studio album
        <em>Map of the Soul: 7 </em> and as a huge ARMY (BTS fan), I've managed
        to listen through the entire album and loved every single track of it! I
        loved it so much that I've used the album cover to make a fursona!
      </p>

      <div id="figure-container">
        <figure>
          <img src="/assets/static/skep-ref-2020.png" style="width: 520px" />
          <figcaption>
            Initial design in 2020, inspired from the colors from
            <em>Map of the Soul: 7</em>
            <br />
            Ref sheet by
            <NuxtLink
              to="https://www.furaffinity.net/view/32456028/"
              class="text-sona-borahae-100 underline"
            >KuteKittyKat</NuxtLink>
            on FurAffinity
          </figcaption>
        </figure>
      </div>

      <div id="figure-container">
        <figure>
          <img src="/assets/static/01.jpg" />
          <figcaption>Crude mspaint headshot drawn in 2020</figcaption>
        </figure>
      </div>

      <p>
        My initial goal was to make the design to be minimal as possible since I
        might have plans to get a fursuit (I know you don't need one but I
        wanted one so bad) for it one day, and it turned out to be just what I
        wanted it to be! It's more of the extended animal version of myself.
      </p>

      <p>
        I also decided to add glasses to reflect more of my tech-savvy side of
        me. I've gotten design inspiration from other furs like Yaps Fox and
        Charm Husky and adopted them to my fursona to have two sides: one being
        shy and timid, while the other side is me being completely obnoxious as
        a whole lol
      </p>

      <div id="figure-container">
        <figure>
          <img src="/assets/static/skep-ref-2022.png" style="width: 520px" />
          <figcaption>5th minor design update with yellow-ish eyes</figcaption>
        </figure>
      </div>

      <p>
        It had a minor update in July 2021 where I have changed the eyes from
        blue to purple to purple to signify "borahae" or "I purple you"; for
        context: it combines two Korean words: Violet (보라; bora) and 'I love
        you' (사랑해; saranghae) - the word "borahae" has become a staple term
        that unites BTS and ARMY. It was coined by V (Kim Taehyung) during a fan
        meeting in 2016. And as the initial definition by Taehyung himself:
      </p>

      <blockquote class="static-block">
        Purple is the last color of the rainbow colors so it means I will trust
        and love you for a long time.
      </blockquote>

      <p>
        In terms of color psychology, the color purple is also associated with
        individualism, royalty, and ambition. It also can boost imagination and
        creativity, on the other, too much purple can cause moodiness.
      </p>

      <div id="figure-container">
        <figure>
          <img src="/assets/static/JakeJune.png" style="width: 15rem" />
          <figcaption>
            <fa-icon :icon="['fab', 'discord']" /> JAKEmegaSNAKE
          </figcaption>
        </figure>
      </div>

      <div id="figure-container">
        <figure>
          <img src="/assets/static/JAKEmegaSNAKE.png" />
          <figcaption>
            <fa-icon :icon="['fab', 'discord']" /> JAKEmegaSNAKE
          </figcaption>
        </figure>
        <figure>
          <img src="/assets/static/ZAMBOY_orig.png" style="width: 26.8rem" />
          <figcaption>
            <fa-icon :icon="['fab', 'discord']" /> ZAMBOYYT
          </figcaption>
        </figure>
      </div>

      <h3>Why the name <em>"Skep"</em>?</h3>
      <p>
        In 2015-2017, the channel name was "FreakingFoxy" and I want to change
        it as I don't want it to be associated with FNAF anymore as the name
        itself is somewhat cringeworthy lol -- until I find a channel called
        "Sethical" and decided to rhyme the word "Sethical" with the word
        "Skeptical" but in all low caps. Then to "Skeptically", and finally
        shortened to simply "Skep" for the sake of simplicity.
      </p>

      <p>
        Then I brought back the name "skep" for its simplicity and kept the name
        "Kokoro Husky" as a stage/artist name instead. Although, there is a
        popular Minecraft YouTuber with the same name
        <em>(*cough* *cough*, Skeppy)</em> and I would 100% deny any
        associations with him whatsoever.
      </p>
      <h3>Why a husky? Why a fox?</h3>
      <p>
        I was initially a husky until when I'm talking to a friend of mine
        talking about the usual furry stuff and immediately had an idea to
        become a fox-husky hybrid; since I equally had a fascination with both
        foxes and huskies with both their traits after looking at some
        interesting facts online.
      </p>
      <p>
        During my childhood, I grew up watching various shows and movies I've
        grown up, most notably The Fox And The Hound 2, the Balto trilogy, Bolt,
        101 Dalmatians, and others. (Most of them are Disney movies; unrelated,
        but I used to watch a lot of <em>Care Bears</em> if you're that old lol)
        But I think that Bolt and Balto are what influenced it, well sort of...
        mainly since I like its pure appearance, courageous, and charismatic
        qualities are what makes me like them the most initially. Including
        foxes as well!
      </p>
    </article>
    <TBA />
  </div>
</template>

<style lang="scss">
#figure-container {
  @apply p-2 flex justify-center gap-x-4;
}

figure {
  @apply flex flex-col items-center gap-y-2;

  img {
    @apply w-[15rem] rounded-md;
  }
}

figcaption {
  @apply text-gray-400 text-sm text-center;
}

.static-block {
  @apply pl-5 py-3 italic relative text-[105%] bg-sona-borahaealt-700 bg-opacity-20;
  &::before {
    content: "";
    @apply absolute top-0 left-0 h-full w-1 bg-sona-borahaealt-600;
  }
}
</style>

// src/pages/about/fursona.tsx
import { Container } from "@/components/Base"
import LazyImg from "@/components/LazyImg"
import { LinkUnderline } from "@/components/Links"
import Notice from "@/components/Notice"
import { cloudinary } from "@/utils/ImgProviders"

export default function Fursona() {
  const t = "Fursona"
  const d = "I'm not cute"

  const fursonaColors = [
    { name: "Brown lol", bgHex: "6d390d", fgHex: "ffe9d7" },
    { name: "Vibrant Orchid", bgHex: "BB3EED", fgHex: "F9ECFE" },
    { name: "Royal Blue", bgHex: "2076C5", fgHex: "E4F0FB" },
    { name: "Sky Cyan", bgHex: "48DDF7", fgHex: "023741" },
    { name: "Bright Yellow", bgHex: "F8D817", fgHex: "372F01" },
    { name: "Pale Orange", bgHex: "FCE392", fgHex: "3C2701" },
    {
      name: "Sclera",
      subtitle: "(white eye part)",
      bgHex: "f3edcd",
      fgHex: "21201c"
    }
  ]

  return (
    <Container title={t} description={d} wrap className="mt-20">
      <Notice
        type="warning"
        content="This page isn't complete and are subject to change. I might be lazy to add or update something in this page lol"
      />
      <section className="flex flex-col items-center gap-y-5 my-10">
        <div
          className="
				relative
				2xl:h-[25rem] 2xl:w-[58.5rem]
				lg:h-[21rem] lg:w-[49.5rem]
				md:h-[18rem] md:w-[40.5rem]
				sm:h-[13.5rem] sm:w-[30rem]
				h-[10.5rem] w-[25rem]
				"
        >
          <LazyImg
            src={cloudinary({
              rootDir: "fursonas",
              dir: "ref-sheets",
              fileName: "ffa-6th-revision_rrvewu.png"
            })}
            className="overflow-hidden rounded-lg"
          />
        </div>
        <span className="text-gray-400">
          {"Ref sheet by "}
          <LinkUnderline
            external
            link="https://www.furaffinity.net/view/32456028/"
            name="KuteKittyKat"
          />
        </span>
      </section>
      <section className="flex flex-col gap-y-2">
        <div className="font-inter flex flex-col lg:flex-row mx-0 lg:mx-auto max-w-[1280px] rounded-lg overflow-x-hidden">
          {fursonaColors.map((color, i) => (
            <div
              key={i}
              className="p-3 h-[7rem] w-[100%] flex flex-col"
              style={{
                backgroundColor: `#${color.bgHex}`,
                color: `#${color.fgHex}`
              }}
            >
              <strong className="text-2xl">{color.name}</strong>
              {color.subtitle ? (
                <span className="text-sm">{color.subtitle}</span>
              ) : null}
              <span>#{color.bgHex.toLowerCase()}</span>
            </div>
          ))}
        </div>
      </section>
      <section className="mx-auto max-w-screen-lg">
        <article className="flex flex-col gap-y-3 my-3 leading-7 text-base lg:leading-8 lg:text-lg">
          <p>
            <strong>Kuroji</strong> is a blue and yellow fox-husky hybrid or
            fusky; and was originally a husky. Wearing thick black glasses and a
            purple t-shirt with white outlines, and completely pantless! (lmao)
          </p>
          <p>
            Mixing with a typical traits both of a fox and a husky, he's a
            wholesome, outgoing, yet weird personality and he easily gets soft
            when he's immediately flattered and starts blushing intensely (lol)
          </p>
          <h3 className="text-2xl lg:text-3xl">Why a husky? Why a fox?</h3>
          <p>
            My fursona was initially a husky until when I'm talking to a friend
            of mine talking about the usual furry stuff and immediately had an
            idea to become a fox-husky hybrid; since I equally had a fascination
            with both foxes and huskies with both their traits after looking at
            some interesting facts online.
          </p>
          <p>
            During my childhood, I grew up watching various shows and movies
            I've grown up, most notably <em>The Fox And The Hound 2</em>, the
            <em>Balto</em> trilogy, <em>Bolt</em>, <em>101 Dalmatians</em>, and
            others. (Most of them are Disney movies; unrelated, but I used to
            watch a lot of <em>Care Bears</em> if you're that old lol) But I
            think that Bolt and Balto are what influenced it, well sort of...
            mainly since I like its pure appearance, courageous, and charismatic
            qualities are what makes me like them the most initially. Including
            foxes as well!
          </p>
        </article>
      </section>
    </Container>
  )
}
