// src/components/Navbar/Navbar.svelte
<script lang="ts">
  import LogoBrand from "~icons/kuro/logo-brand?raw";
  import SearchIcon from "~icons/lucide/search?raw";

  const navLinks = [
    { href: "/portfolio", text: "Portfolio" },
    { href: "/blog", text: "Blog" },
    { href: "/about", text: "About" },
  ];
</script>

<a
  href="#skip-to-content"
  class="fixed top-2 left-2 pointer-events-none focus:pointer-events-auto focus:opacity-100 focus:translate-x-0 translate-x-full opacity-0 bg-kuro-lavender-700 z-50 px-4 py-2.5 rounded-md"
  data-astro-prefetch="false">Skip to content?</a
>
<div class="z-20 sticky top-0 bg-kuro-dark2">
  <nav class="py-1.5 flex justify-between px-6 max-w-screen-xl mx-auto">
    <a
      href="/"
      title="Home page"
      class="py-2 pr-1 flex-shrink-0 [&_svg]:!h-[1.33rem]"
    >
      {@html LogoBrand}
    </a>
    <div
      id="global-nav"
      class="w-full justify-end my-auto flex items-center gap-x-1 font-kuro-mono text-sm"
    >
      {#each navLinks as { href, text }}
        <a {href} class="px-3 py-1.5">
          {text}
        </a>
      {/each}
    </div>
    <button class="px-3 py-2 cursor-pointer">
      {@html SearchIcon}
    </button>
  </nav>
</div>

// sites/blog/src/components/base/Navbar.vue
<script setup lang="ts">
import { ref, onMounted } from "vue"
import kLogo from "../k-logo.vue"

const categories = [
  "Insights",
  "Updates",
  "Design",
  "Engineering",
  "Others",
  "Music"
]

const shelfToggle = ref(false)

const kuroIconRef = ref<HTMLElement | null>(null)
const shelfBlog = ref<HTMLElement | null>(null)
const shelfKuro = ref<HTMLElement | null>(null)

onMounted(() => {})
</script>

<template>
  <header class="bg-kuro-dark1 sticky top-0 z-[2]">
    <nav class="flex items-center max-w-screen-2xl py-4 px-9 mx-auto">
      <div class="flex items-center w-full gap-x-3.5">
        <button ref="kuroIconRef" class="cursor-pointer">
          <kLogo />
        </button>
        <span class="mx-1 text-2xl opacity-50 select-none">/</span>
        <div class="relative flex items-center">
          <a
            ref="shelfBlog"
            id="shelf-blog"
            href="/"
            class="absolute -top-2 left-0 transition-[transform,opacity] duration-300 inline-flex gap-x-3.5 items-center font-bold text-3xl"
            :class="[
              shelfToggle
                ? 'translate-y-6 opacity-0 scale-y-50 pointer-events-none'
                : ''
            ]"
          >
            <img
              src="/favicon.png"
              alt="Kuroji drawn by MintyChipMocha"
              width="33px"
              class="aspect-square"
            />
            Blog
          </a>
          <div
            ref="shelfKuro"
            id="shelf-kuro"
            class="transition-[transform,opacity] duration-300 inline-flex gap-x-3.5 items-center"
            :class="[
              !shelfToggle
                ? '-translate-y-6 opacity-0 scale-y-50 pointer-events-none'
                : ''
            ]"
          >
            content
          </div>
        </div>
      </div>
      <div class="flex items-center w-full justify-end text-[1.025rem]">
        <span
          class="transition-colors duration-150 group px-3.5 py-2.5 rounded-md relative select-none hover:bg-kuro-lavender-700 hover:bg-opacity-50"
        >
          Categories
          <div
            class="py-3 group-hover:opacity-100 group-focus:opacity-100 group group-hover:pointer-events-auto group-hover:translate-y-0 group-focus:translate-y-0 translate-y-1 ease-in-out transition-[opacity,transform] duration-200 opacity-0 pointer-events-none absolute left-0 top-10"
          >
            <div
              class="bg-kuro-dark2 p-2 grid rounded-md border border-kuro-violet-600"
            >
              <a
                v-for="(item, index) in categories"
                :key="index"
                :href="`/category/${item.toLocaleLowerCase()}`"
                class="transition-colors duration-150 px-3 py-2.5 hover:bg-kuro-lavender-600 hover:bg-opacity-75 rounded-md"
              >
                {{ item }}
              </a>
            </div>
          </div>
        </span>
        <a
          href="/about-me"
          class="transition-colors duration-200 px-3.5 py-2.5 rounded-md relative select-none hover:bg-kuro-lavender-700 hover:bg-opacity-50"
        >
          About me
        </a>
      </div>
    </nav>
  </header>
</template>
