// components/BaseHead.tsx
import Head from "next/head";

interface IBaseHeadProps {
  title: string;
  description: string;
  url?: string;
  keywords?: string[];
}
export default function BaseHead({ title, description, url, keywords }: IBaseHeadProps) {
  const SITE_NAME = 'skepfusky'

  return(
    <Head>
      <title>{title} - {SITE_NAME}</title>
      <meta name="description" content={description} />
      <meta name="keywords" content={keywords?.join(', ')} />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
      <link rel="apple-touch-icon" href="/favicon.ico" />
      <meta property="og:title" content={title} />
      <meta property="og:description" content={description} />
      <meta property="og:url" content={url} />
      {/* <meta property="og:image" content="https://www.example.com/image.jpg" /> */}
      <meta property="og:type" content="website" />
      <meta property="og:site_name" content={SITE_NAME} />
      <meta name="twitter:card" content="summary" />
      <meta name="twitter:creator" content="@skepfuskyjs" />
      <meta name="twitter:title" content={title} />
      <meta name="twitter:description" content={description} />
      <meta name="theme-color" content="#fff" />
      {/* <meta name="twitter:image" content="https://www.example.com/image.jpg" /> */}
    </Head>
  )
};

export function BaseHeadLanding() {
  const description = "A website for skepfusky's works and stuff, I dunno";
  
  return (
    <Head>
      <title>skepfusky</title>
      <meta name="description" content={description} />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
      <link rel="apple-touch-icon" href="/favicon.ico" />
      <meta property="og:title" content="skepfusky" />
      <meta property="og:description" content={description} />
      <meta property="og:image" content="/static/avatars/07.jpg" />
      <meta property="og:type" content="website" />
      <meta property="og:site_name" content="skepfusky" />
      <meta name="twitter:card" content="summary" />
      <meta name="twitter:creator" content="@skepfuskyjs" />
      <meta name="twitter:title" content="skepfusky" />
      <meta name="twitter:description" content={description} />
      <meta name="theme-color" content="#fff" />
      <meta name="twitter:image" content="/static/avatars/07.jpg" />
    </Head>
  );
}

// components/BaseHead.vue
<script setup lang="ts">
const props = withDefaults(
  defineProps<{
    title?: string;
    description?: string;
    keywords?: string[] | any;
    img?: string;
    isDefaultIndex?: boolean;
  }>(),
  {
    title: "",
    description: "",
    keywords: ["programming", "music", "skepfusky", "kokoro husky", "yes"],
    img: "",
  }
);

const SITE_TITLE = ref("skepfusky");
</script>

<template>
  <Head>
    <Title>{{ title }} - {{ SITE_TITLE }}</Title>
    <Meta name="title" :content="`${title} - ${SITE_TITLE}`" />
    <Meta name="description" :content="description" />
    <Meta property="og:title" :content="`${title} - ${SITE_TITLE}`" />
    <Meta property="og:description" :content="description" />
    <Meta name="twitter:title" :content="`${title} - ${SITE_TITLE}`" />
    <Meta name="twitter:description" :content="description" />

    <!-- No change -->
    <Meta rel="shortcut icon" href="/favicon.ico" />
    <Meta v-if="keywords" name="keywords" :content="keywords?.join(', ')" />
    <Meta v-if="img" name="image" :content="img" />
    <Meta property="og:type" content="website" />
    <Meta v-if="img" property="og:image" :content="img" />
    <Meta name="twitter:card" content="summary_large_image" />
    <Meta v-if="img" name="twitter:image" :content="img" />
  </Head>
</template>
