// src/components/Base/Container.tsx
import { useRouter } from "next/router"
import Head from "next/head"
import { LayoutProps } from "./Layout"

interface ContainerProps extends LayoutProps {
  title: string
  description: string
  className?: string
  wrap?: boolean
}

export function Container(props: ContainerProps) {
  const router = useRouter()
  const url = `https://skepfusky.xyz${router.asPath}`

  const title =
    router.pathname == "/" ? props.title : `${props.title} | skepfusky`

  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content={props.description} />
        <meta property="og:title" content={title} />
        <meta property="og:description" content={props.description} />
        <meta property="og:url" content={url} />
        <meta property="og:type" content="website" />
        <meta name="twitter:card" content="summary" />
        <meta name="twitter:title" content={props.title} />
        <meta name="twitter:description" content={props.description} />
        <meta name="twitter:url" content={url} />
        <meta name="twitter:site" content="@skepfuskyjs" />
        <meta name="twitter:creator" content="@skepfuskyjs" />
        <link rel="canonical" href={url} />
      </Head>
      <main
        className={
          !props.wrap
            ? "relative z-1"
            : "relative z-1 max-w-screen-2xl mx-auto px-7"
        }
      >
        {props.children}
      </main>
    </>
  )
}

// components/Container.vue
<template>
	<main>
		<slot />
	</main>
</template>

<script setup lang="ts">
const props = defineProps<{ title: string; description?: string }>()

const router = useRoute()
const fullUrl = `https://kurofusky.xyz${router.fullPath}`

useHead({
	title: props.title,
	link: [{ rel: "canonical", href: fullUrl }],
	meta: [
		{ name: "description", content: props.description },
		{ name: "twitter:title", content: props.title },
		{ name: "twitter:description", content: props.description },
		{ name: "twitter:site", content: "@kurojifusky" },
		{ name: "twitter:creator", content: "@kurojifusky" },
		{ name: "twitter:card", content: "summary_large_image" },
		{ name: "twitter:url", content: fullUrl },
		{ property: "og:url", content: fullUrl },
		{ property: "og:description", content: props.description },
		{ property: "og:site_name", content: "Kuroji Dump" },
		{ property: "og:type", content: "website" },
	],
})
</script>

<style scoped></style>
