// apps/blog/src/components/base/Footer.vue
<script setup lang="ts">
import { IconGithub, IconYoutube, IconXTwitter, IconMastodon } from "@iconify-prerendered/vue-fa6-brands"
import type { SVGAttributes, VNode } from "vue";

type IterableLinks = Array<{
  name: string
  icon?: NonNullable<(p?: SVGAttributes) => VNode>
  link: string
}>

const socialLinks: IterableLinks = [
  { name: "YouTube", icon: IconYoutube, link: "https://www.youtube.com/@kurojifusky" },
  { name: "GitHub", icon: IconGithub, link: "https://github.com/kuroji-fusky" },
  { name: "Mastodon", icon: IconMastodon, link: "https://furry.engineer/@kurojifusky" },
  { name: "X, formerly known as Twitter", icon: IconXTwitter, link: "https://x.com/kurojifusky" },
]

const otherLinks: IterableLinks = [
  { name: "View source code", link: "https://github.com" },
  { name: "Support my work on Ko-fi", link: "https://ko-fi.com/kuroji_fusky" },
]
</script>

<template>
  <footer class="px-9 max-w-screen-2xl mx-auto flex items-center gap-x-3 py-6">
    <span id="copyright">&copy; 2023 Kerby Keith Aquino / Fusky Labs LLC</span>
    <div class="flex gap-x-5 ml-auto">
      <a v-for="({ name, icon, link }, i) in socialLinks" :key="i" :href="link" :title="name"
        :rel="name !== 'Mastodon' ? 'nofollow noreferrer' : 'me'" target="_blank"
        class="hover:text-kuro-lavender-400 transition-colors">
        <component :is="(icon as {})" height="1.33rem" width="1.33rem" class="p-0.5" />
      </a>
    </div>
    <hr class="h-6 border border-l-kuro-lavender-700 mx-2">
    <div class="flex gap-x-3.5">
      <a v-for="({ name, link }, index) in otherLinks" :key="index" :href="link" target="_blank" rel="noreferrer"
        class="hover:underline hover:text-kuro-lavender-400 transition-colors">
        {{ name }}
      </a>
    </div>
  </footer>
</template>

// src/components/Base/Footer.tsx
import Link from "next/link"
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome"
import Backdrop from "../Backdrop"
import { LinkUnderline } from "../Links"
import socials from "./Socials"

export default function Footer() {
  return (
    <footer className="relative mt-[15rem]">
      <div className="mx-auto max-w-screen-2xl flex flex-col lg:flex-row justify-between items-center gap-y-5 px-12 z-4 absolute p-6 pb-[2.75rem] lg:pb-[4.5rem] bottom-0 left-0 right-0 text-center">
        <div className="translate-y-0 opacity-100 transition-all duration-500 text-left flex flex-col gap-3.5">
          <div role="list" className="flex gap-8 flex-wrap justify-center">
            {socials.map((items, index) => (
              <Link key={index} href={items.link} passHref>
                <a
                  role="listitem"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="hover:text-sona-borahae-400"
                >
                  <FontAwesomeIcon icon={items.icon} size="lg" />
                </a>
              </Link>
            ))}
          </div>
        </div>

        <div
          id="other-shit"
          className={`translate-y-0 opacity-100 transition-all duration-500 font-jetbrains-mono flex flex-col gap-y-3 items-center lg:items-end`}
        >
          <div className="flex flex-col items-center gap-y-2">
            <div className="flex flex-wrap justify-center gap-4 text-sm">
              <LinkUnderline
                external
                link="https://github.com/kuroji-fusky/kurofusky.xyz"
                name="Website source code"
              />
              <LinkUnderline
                external
                link="https://ko-fi.com/skepfusky"
                name="Support me on Ko-Fi"
              />
            </div>
          </div>
          <span id="copyright" className="text-sm mt-1">
            {`©  2014-${new Date().getFullYear()} Kerby Keith Aquino`}
          </span>
        </div>
      </div>
      {/* Backdrop */}
      <div className="opacity-100 transition-all duration-1000 h-[24rem] w-full absolute bottom-0 overflow-hidden">
        <Backdrop className="-bottom-[1rem] -left-4 opacity-10 rotate-4 h-[11rem] w-[60%] bg-sona-skycyan-700" />
        <Backdrop className="-bottom-[2rem] opacity-10 left-[30%] h-[10rem] w-[40%] bg-sona-borahaealt-800" />
        <Backdrop className="-bottom-[1rem] -right-4 opacity-10 -rotate-4 h-[11rem] w-[60%] bg-sona-magenta-800" />
      </div>
    </footer>
  )
}
