// src/components/Navbar/Navbar.svelte
<script lang="ts">
  import LogoBrand from "~icons/kuro/logo-brand?raw";
  import SearchIcon from "~icons/lucide/search?raw";

  const navLinks = [
    { href: "/portfolio", text: "Portfolio" },
    { href: "/blog", text: "Blog" },
    { href: "/about", text: "About" },
  ];
</script>

<a
  href="#skip-to-content"
  class="fixed top-2 left-2 pointer-events-none focus:pointer-events-auto focus:opacity-100 focus:translate-x-0 translate-x-full opacity-0 bg-kuro-lavender-700 z-50 px-4 py-2.5 rounded-md"
  data-astro-prefetch="false">Skip to content?</a
>
<div class="z-20 sticky top-0 bg-kuro-dark2">
  <nav class="py-1.5 flex justify-between px-6 max-w-screen-xl mx-auto">
    <a
      href="/"
      title="Home page"
      class="py-2 pr-1 flex-shrink-0 [&_svg]:!h-[1.33rem]"
    >
      {@html LogoBrand}
    </a>
    <div
      id="global-nav"
      class="w-full justify-end my-auto flex items-center gap-x-1 font-kuro-mono text-sm"
    >
      {#each navLinks as { href, text }}
        <a {href} class="px-3 py-1.5">
          {text}
        </a>
      {/each}
    </div>
    <button class="px-3 py-2 cursor-pointer">
      {@html SearchIcon}
    </button>
  </nav>
</div>

// apps/blog/components/Navbar.vue
<script setup lang="ts">
const NAVBAR_ITEMS = ["Engineering", "Updates", "Others"]
</script>

<template>
  <header
    class="sticky top-0 mb-3 z-[5] bg-opacity-[0.75] bg-kuro-dark2 backdrop-blur-sm"
  >
    <nav
      class="flex items-center justify-between max-w-screen-xl py-5 mx-auto px-9"
    >
      <NuxtLink href="/">kuro blog logo</NuxtLink>
      <ol class="flex gap-5">
        <li
          class="text-lg font-medium select-none font-inter"
          v-for="(text, index) in NAVBAR_ITEMS"
          :key="index"
        >
          <NuxtLink :to="`/${text.toLocaleLowerCase()}`">
            {{ text }}
          </NuxtLink>
        </li>
        <li class="relative group">
          <span class="text-lg font-medium select-none font-inter">
            About Me
          </span>
          <div
            class="absolute right-0 pt-10 transition-all translate-y-0.5 rounded-md opacity-0 pointer-events-none top-5 group-hover:pointer-events-auto group-hover:translate-y-0 group-hover:opacity-100"
          >
            <div class="relative px-4 py-2.5 rounded-lg bg-kuro-dark1 -top-3.5">
              lmao
            </div>
          </div>
        </li>
      </ol>
    </nav>
  </header>
</template>
