// components/Container.vue
<template>
	<main>
		<slot />
	</main>
</template>

<script setup lang="ts">
const props = defineProps<{ title: string; description?: string }>()

const router = useRoute()
const fullUrl = `https://kurofusky.xyz${router.fullPath}`

useHead({
	title: props.title,
	link: [{ rel: "canonical", href: fullUrl }],
	meta: [
		{ name: "description", content: props.description },
		{ name: "twitter:title", content: props.title },
		{ name: "twitter:description", content: props.description },
		{ name: "twitter:site", content: "@kurojifusky" },
		{ name: "twitter:creator", content: "@kurojifusky" },
		{ name: "twitter:card", content: "summary_large_image" },
		{ name: "twitter:url", content: fullUrl },
		{ property: "og:url", content: fullUrl },
		{ property: "og:description", content: props.description },
		{ property: "og:site_name", content: "Kuroji Dump" },
		{ property: "og:type", content: "website" },
	],
})
</script>

<style scoped></style>

// src/lib/components/Container.svelte
<script lang="ts">
	import { page } from '$app/stores';
	import Footer from './Footer.svelte';

	export let title = 'Kuroji Fusky';
	export let description = 'Yes';
	export let hideFooterLanding = false;
	let URL: string = $page.url.origin + $page.url.pathname;
</script>

<svelte:head>
	<title>{title}</title>
	<link rel="canonical" href={URL} />
	<meta name="description" content={description} />
	<meta property="og:title" content={title} />
	<meta property="og:description" content={description} />
	<meta property="og:url" content={URL} />
	<meta property="og:type" content="website" />
	<meta name="twitter:title" content={title} />
	<meta name="twitter:description" content={description} />
	<meta name="twitter:url" content={URL} />
</svelte:head>

<main>
	<slot />
</main>
{#if !hideFooterLanding}
	<Footer />
{/if}
