// components/Container.vue
<template>
  <main>
    <slot />
  </main>
</template>

<script setup lang="ts">
const props = defineProps<{ title: string; description?: string }>()
useHead({
  title: props.title,
  meta: [
    { name: "description", content: props.description },
    { name: "twitter:title", content: props.title },
    { name: "twitter:description", content: props.description },
    { name: "twitter:owner", content: "@kurojifusky" },
    { name: "twitter:creator", content: "@kurojifusky" },
    { name: "twitter:card", content: "summary_large_image" },
    { property: "og:title", content: props.title },
    { property: "og:description", content: props.description },
    { property: "og:site_name", content: "Kuroji Dump" },
    { property: "og:type", content: "website" },
  ],
})
</script>

<style scoped></style>

// src/components/ui/Container.tsx
import Head from "next/head"

interface ContainerProps {
  children: React.ReactNode
  t: string
  d?: string
  className?: string
}

export default function Container(props: ContainerProps) {
  const { t: title, d: description } = props

  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content={description} />
        <meta property="og:title" content={title} />
        <meta property="og:description" content={description} />
        <meta property="og:type" content="website" />
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content={title} />
        <meta name="twitter:description" content={description} />
      </Head>
      <main className={props.className}>{props.children}</main>
    </>
  )
}
