// portfolio/src/components/Base/Footer.tsx
import Link from "next/link"
import { SiKofi as Kofi } from "react-icons/si"
import {
  FaYoutube as Youtube,
  FaMastodon as Mastodon,
  FaGithub as Github,
  FaTelegram as Telegram
} from "react-icons/fa6"
import { RiTwitterXFill as XTwitter } from "react-icons/ri"

export default function Footer() {
  const socials = [
    {
      link: "www.youtube.com/@kurojifusky",
      icon: Youtube,
      rel: "noreferrer noopenner"
    },
    { link: "furry.engineer/@kurojifusky", icon: Mastodon, rel: "me" },
    {
      link: "github.com/kuroji-fusky",
      icon: Github,
      rel: "noreferrer noopenner"
    },
    {
      link: "telegram.me/kurojifusky",
      icon: Telegram,
      rel: "noreferrer noopenner"
    },
    {
      link: "twitter.com/kurojifusky",
      icon: XTwitter,
      rel: "noreferrer noopenner"
    },
    { link: "ko-fi.com/kuroji_fusky", icon: Kofi, rel: "noreferrer noopenner" }
  ]

  return (
    <footer className="border-t border-kuro-lavender-200 px-12 py-8 flex justify-between items-center text-sm">
      <div className="flex gap-5 items-center">
        <span>
          {"Version "}
          <span className="font-bold bg-gradient-to-br from-kuro-royalblue-400 to-kuro-lavender-500 bg-clip-text text-transparent">
            8
          </span>
        </span>
        <hr className="border-l-2 border-kuro-lavender-200 h-6 opacity-50" />
        <div className="flex gap-x-5 items-center">
          {socials.map((item, index) => (
            <Link
              href={`https://${item.link}`}
              key={index}
              rel={item.rel}
              target="_blank"
            >
              <item.icon size="1.35em" />
            </Link>
          ))}
        </div>
      </div>
      <span>
        {`© 2009-${new Date().getFullYear()} Kerby Keith Aquino / Fusky Labs, LLC`}
      </span>
    </footer>
  )
}

// apps/blog/src/components/base/Footer.vue
<script setup lang="ts">
import { IconGithub, IconYoutube, IconXTwitter, IconMastodon } from "@iconify-prerendered/vue-fa6-brands"
import type { SVGAttributes, VNode } from "vue";

type IterableLinks = Array<{
  name: string
  icon?: NonNullable<(p?: SVGAttributes) => VNode>
  link: string
}>

const socialLinks: IterableLinks = [
  { name: "YouTube", icon: IconYoutube, link: "https://www.youtube.com/@kurojifusky" },
  { name: "GitHub", icon: IconGithub, link: "https://github.com/kuroji-fusky" },
  { name: "Mastodon", icon: IconMastodon, link: "https://furry.engineer/@kurojifusky" },
  { name: "X, formerly known as Twitter", icon: IconXTwitter, link: "https://x.com/kurojifusky" },
]

const otherLinks: IterableLinks = [
  { name: "View source code", link: "https://github.com" },
  { name: "Support my work on Ko-fi", link: "https://ko-fi.com/kuroji_fusky" },
]
</script>

<template>
  <footer class="px-9 max-w-screen-2xl mx-auto flex items-center gap-x-3 py-6">
    <span id="copyright">&copy; 2023 Kerby Keith Aquino / Fusky Labs LLC</span>
    <div class="flex gap-x-5 ml-auto">
      <a v-for="({ name, icon, link }, i) in socialLinks" :key="i" :href="link" :title="name"
        :rel="name !== 'Mastodon' ? 'nofollow noreferrer' : 'me'" target="_blank"
        class="hover:text-kuro-lavender-400 transition-colors">
        <component :is="(icon as {})" height="1.33rem" width="1.33rem" class="p-0.5" />
      </a>
    </div>
    <hr class="h-6 border border-l-kuro-lavender-700 mx-2">
    <div class="flex gap-x-3.5">
      <a v-for="({ name, link }, index) in otherLinks" :key="index" :href="link" target="_blank" rel="noreferrer"
        class="hover:underline hover:text-kuro-lavender-400 transition-colors">
        {{ name }}
      </a>
    </div>
  </footer>
</template>
